### ISSUE TITLE
Automatic parameter optimization of gridsearch

### ISSUE THREAD

**Issue by Benczus** [Benczus/inversion_api#29]
- [ ] create  method which runs for a given amount of epochs 
- [ ] method is able to automatically optimize parameters of the given model by generating a parameter space from the given model.
- [ ] parameter space generation could be done by different methods:
- Randomly change the given parameters by a small margin
- Use a genetic algorithm
- Use gradient descent
